// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFCK8HxX3iAaKHHgVOeVR4WPv3y0TJq18',
    appId: '1:64200159819:web:8c1830c60615f18d5913ce',
    messagingSenderId: '64200159819',
    projectId: 'jati-presensi',
    authDomain: 'jati-presensi.firebaseapp.com',
    storageBucket: 'jati-presensi.appspot.com',
    measurementId: 'G-HQX2R1RV2H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDui1oQJBwVoDOZ_ejqSkjIN26v0uIMLYY',
    appId: '1:64200159819:android:e5f45f7709d9c5605913ce',
    messagingSenderId: '64200159819',
    projectId: 'jati-presensi',
    storageBucket: 'jati-presensi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1LEy4IYMUTuAcViPkMblrCf_lpjZwJDo',
    appId: '1:64200159819:ios:f4b38a380d4335705913ce',
    messagingSenderId: '64200159819',
    projectId: 'jati-presensi',
    storageBucket: 'jati-presensi.appspot.com',
    iosBundleId: 'com.example.jatiPresensi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1LEy4IYMUTuAcViPkMblrCf_lpjZwJDo',
    appId: '1:64200159819:ios:f4b38a380d4335705913ce',
    messagingSenderId: '64200159819',
    projectId: 'jati-presensi',
    storageBucket: 'jati-presensi.appspot.com',
    iosBundleId: 'com.example.jatiPresensi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFCK8HxX3iAaKHHgVOeVR4WPv3y0TJq18',
    appId: '1:64200159819:web:c9e6ee77903ab6895913ce',
    messagingSenderId: '64200159819',
    projectId: 'jati-presensi',
    authDomain: 'jati-presensi.firebaseapp.com',
    storageBucket: 'jati-presensi.appspot.com',
    measurementId: 'G-27J7HK5RTS',
  );
}
